---
- name: Configure static routes
  cisco.ios.ios_config:
    lines:
      - "ip route {{ item.prefix }} {{ item.mask }} {{ item.next_hop }}"
    save_when: always
  loop: "{{ configure_static_routes | default([]) }}"
  when:
    - configure_static_routes is defined
    - configure_static_routes | length > 0

- name: Show configured static routes
  cisco.ios.ios_command:
    commands:
      - show ip route static
  register: configure_static_route_output
  when:
    - configure_static_routes is defined
    - configure_static_routes | length > 0

- name: Display static routes status
  ansible.builtin.debug:
    var: configure_static_route_output.stdout_lines
  when:
    - configure_static_routes is defined
    - configure_static_routes | length > 0
