---
- name: Configure IP Addresses on Hosts
  hosts: all
  gather_facts: false
  tasks:
    - name: Show version
      cisco.ios.ios_command:
        commands:
          - show version
  # =========================
  # R1
  # =========================
    - name: Configure R1 Ethernet0/0
      when: hosts_hostname == "R1"
      cisco.ios.ios_config:
        parents: "interface Ethernet0/0"
        lines:
          - ip address 192.168.12.1 255.255.255.0
          - no shutdown
        save_when: always
