---
- name: Configure IP addresses and enable interfaces
  hosts: routers
  gather_facts: false

  tasks:

    # =========================
    # R1
    # =========================

    - name: Configure R1 Ethernet0/0
      when: inventory_hostname == "R1"
      cisco.ios.ios_config:
        parents: "interface Ethernet0/0"
        lines:
          - ip address 192.168.12.1 255.255.255.0
          - no shutdown
        save_when: always

    - name: Configure R1 Ethernet0/1
      when: inventory_hostname == "R1"
      cisco.ios.ios_config:
        parents: "interface Ethernet0/1"
        lines:
          - ip address 192.168.10.1 255.255.255.0
          - no shutdown
        save_when: always

    # =========================
    # R2
    # =========================

    - name: Configure R2 Ethernet0/0
      when: inventory_hostname == "R2"
      cisco.ios.ios_config:
        parents: "interface Ethernet0/0"
        lines:
          - ip address 192.168.12.2 255.255.255.0
          - no shutdown
        save_when: always

    - name: Configure R2 Ethernet0/1
      when: inventory_hostname == "R2"
      cisco.ios.ios_config:
        parents: "interface Ethernet0/1"
        lines:
          - ip address 192.168.23.2 255.255.255.0
          - no shutdown
        save_when: always

    # =========================
    # R3
    # =========================

    - name: Configure R3 Ethernet0/0
      when: inventory_hostname == "R3"
      cisco.ios.ios_config:
        parents: "interface Ethernet0/0"
        lines:
          - ip address 192.168.23.3 255.255.255.0
          - no shutdown
        save_when: always

    - name: Configure R3 Ethernet0/1
      when: inventory_hostname == "R3"
      cisco.ios.ios_config:
        parents: "interface Ethernet0/1"
        lines:
          - ip address 192.168.2.1 255.255.255.0
          - no shutdown
        save_when: always

    - name: Disable automatic network configuration loading
      cisco.ios.ios_config:
        lines:
          - no boot network
          - no boot host
          - no service config
        save_when: always
