---
- name: Configure IP Addresses on Hosts
  hosts: all
  gather_facts: false
  tasks:
    - name: Show version
      cisco.ios.ios_command:
        commands:
          - show version

    - name: Configure Layer 3 IP Addresses
      cisco.ios.ios_l3_interfaces:
        config: "{{ router_interfaces }}"
        state: merged
