---
name: Ansible CI

'on':
  workflow_dispatch: {}
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Ansible
        run: |
          pip install ansible
          pip install ansible-lint
          pip install yamllint

      - name: Install Cisco Collection
        run: |
          ansible-galaxy collection install cisco.ios
          printf '%s' "$ANSIBLE_VAULT_PASSWORD" > .vault_pass
          chmod 600 .vault_pass

      - name: YAML Check
        run: |
          yamllint .

      - name: Syntax Check - Show Running Config
        run: |
          ansible-playbook playbooks/show_running_config.yml --syntax-check

      - name: Syntax Check - Show Running Config
        run: |
          ansible-playbook playbooks/restore_config.yml --syntax-check

      - name: Syntax Check - Show Running Config
        run: |
          ansible-playbook playbooks/deploy_config.yml --syntax-check

      - name: Ansible Lint
        run: |
          ansible-lint

      - name: Remove temporary Vault password
        if: always()
        run: rm -f .vault_pass
