---
name: Backup Router Ansible

'on':
  workflow_dispatch:
    inputs:
      target_device:
        description: 'Select the device or group to configure'
        required: true
        default: 'routers'
        type: choice
        options:
          - routers
          - R1
          - R2
          - R3

permissions:
  contents: write

jobs:
  bakup:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to Ubuntu Server
        run: |
          ansible-galaxy collection install -r requirements.yml

          if [ "${{ github.event.inputs.target_device }}" = "routers" ]; then
            ansible-playbook playbooks/show_running_config.yml
          else
          ansible-playbook \
            playbooks/show_running_config.yml \
            --limit "${{ github.event.inputs.target_device }}"
          fi

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Commit router backups
        run: |
          git add configs/

          if git diff --cached --quiet; then
            echo "No configuration changes."
          else
            git commit -m "Router backup $(date '+%Y-%m-%d %H:%M:%S')"
            git push origin main
          fi
